#!/usr/bin/env bash
# Installs nginx on a server and configure it to serve

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx start
