#!/usr/bin/env bash
# manages manage_my_process by either starting it, stopping it or restarting it.

command="$1"

if [ -z "$command" ]; then
  echo "Usage: $0 {start|stop|restart}"
  exit 1
fi

if [ "$command" == "start" ]; then

  bash ./manage_my_process &
  echo "$!" > /var/run/my_process.pid
  echo "manage_my_process started"

elif [ "$command" == "stop" ]; then
  if [ -e "/var/run/my_process.pid" ]; then
    pkill -f './manage_my_process' && rm /var/run/my_process.pid
    echo "manage_my_process stopped"
  else
    echo "manage_my_process is not running"
    exit 1
  fi

elif [ "$command" == "restart" ]; then

  "$0" stop >& /dev/null
  "$0" start >& /dev/null
  echo "manage_my_process restarted"

else
  echo "Usage: $0 {start|stop|restart}" 
  exit 1
fi
