#!/usr/bin/env bash
# fizzbuzz

file="/etc/passwd"

while IFS=: read -r user pass uid gid info dir shell; do
  echo "The user $user is part of the $gid gang, lives in $dir and rides $shell. $uid's place is protected by the passcode $pass, more info about the user here: $info"
done < "$file"
