#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

for (( count=1; count<=10; count++ ))
do
  if [ $count -eq 9 ]
  then
    echo "Best School"
    echo "Hi"
  else
    echo "Best School"
  fi
done
