#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# display time for 12 hours and 59 minutes

hour=0

while [ "$hour" -le 12 ]; do
  echo "Hour: $hour"
  
  minute=1
  
  while [ "$minute" -lt 60 ]; do
    echo "$minute"
    minute=$((minute + 1))
  done

  hour=$((hour + 1))
done